### ISSUE TITLE
передача массивов в функцию

### ISSUE THREAD

**Issue by omon03** [GuschinS/ELE#1]
передача массивов в функцию при её вызове производится без скобок.
```cpp
main()
{
    fun(arr);
}
```
при объявлении:
```cpp
fun(arr{})  // обязательно фигурные скобки
{
    // code
}
```

**Comment by omon03** [comment]
https://github.com/GuschinS/ELE/blob/ad37592bd7879f1a580d387adda29a330bf99a54/test.cpp#L94

**Comment by omon03** [comment]
https://github.com/GuschinS/ELE/blob/b1681f5d932674c027ca912d10072b3a9385c346/test.cpp#L57
а вот переменную надо передавать без скобок

**Comment by GuschinS** [comment]
После первого коментария добавил скобки не разобравшись, что речь о передаче архива, а не переменной.
Исправил обратно.

**Comment by omon03** [comment]
если всё исправлено, надо закрыть вопрос.
